-- =============================================
-- MINISTRY OF EDUCATION DATA SEED
-- Description: Bulk insert of real subject combinations from official portal
-- =============================================

-- 1. ARTS & SPORTS SCIENCE > SPORTS
-- Combinations: AS2009, AS2006, AS2011, AS2027...
WITH track AS (SELECT id, pathway_id FROM tracks WHERE code = 'SPORTS'),
     pathway AS (SELECT id FROM pathways WHERE code = 'ARTS')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'AS2009', ARRAY['Biology', 'Geography', 'Sports & Recreation'], ARRAY['Sports Management', 'Ecotherapy'], 3.8, 'MEDIUM'),
((SELECT id FROM track), 'AS2006', ARRAY['Biology', 'Islamic Religious Education', 'Sports & Recreation'], ARRAY['Sports Coaching'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2011', ARRAY['Biology', 'History & Citizenship', 'Sports & Recreation'], ARRAY['Sports History', 'Administration'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS2027', ARRAY['General Science', 'Literature in English', 'Sports & Recreation'], ARRAY['Sports Journalism'], 3.7, 'MEDIUM'),
((SELECT id FROM track), 'AS2026', ARRAY['General Science', 'History & Citizenship', 'Sports & Recreation'], ARRAY['Sports Administration'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2013', ARRAY['Biology', 'Mandarine Chinese', 'Sports & Recreation'], ARRAY['International Sports Management'], 4.0, 'HIGH'),
((SELECT id FROM track), 'AS2029', ARRAY['Core Mathematics', 'General Science', 'Sports & Recreation'], ARRAY['Sports Analytics', 'Kinesiology'], 4.2, 'HIGH'),
((SELECT id FROM track), 'AS2003', ARRAY['Biology', 'Computer Studies', 'Sports & Recreation'], ARRAY['Sports Technology', 'Performance Analysis'], 4.3, 'HIGH'),
((SELECT id FROM track), 'AS2021', ARRAY['General Science', 'Hindu Religious Education', 'Sports & Recreation'], ARRAY['Sports Coaching'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2001', ARRAY['Arabic', 'Biology', 'Sports & Recreation'], ARRAY['International Sports'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS2030', ARRAY['General Science', 'Media Technology', 'Sports & Recreation'], ARRAY['Sports Broadcasting'], 4.0, 'HIGH'),
((SELECT id FROM track), 'AS2005', ARRAY['Biology', 'Hindu Religious Education', 'Sports & Recreation'], ARRAY['Sports Coaching'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2020', ARRAY['General Science', 'Islamic Religious Education', 'Sports & Recreation'], ARRAY['Sports Coaching'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2014', ARRAY['Core Mathematics', 'Biology', 'Sports & Recreation'], ARRAY['Sports Medicine'], 4.5, 'HIGH'),
((SELECT id FROM track), 'AS2017', ARRAY['Business Studies', 'General Science', 'Sports & Recreation'], ARRAY['Sports Marketing'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'AS2002', ARRAY['Biology', 'Business Studies', 'Sports & Recreation'], ARRAY['Sports Management'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'AS2024', ARRAY['General Science', 'Geography', 'Sports & Recreation'], ARRAY['Outdoor Recreation'], 3.7, 'LOW'),
((SELECT id FROM track), 'AS2018', ARRAY['Computer Studies', 'General Science', 'Sports & Recreation'], ARRAY['E-Sports', 'Data Analysis'], 4.1, 'HIGH'),
((SELECT id FROM track), 'AS2028', ARRAY['General Science', 'Mandarine Chinese', 'Sports & Recreation'], ARRAY['International Sports'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS2007', ARRAY['Biology', 'Fasihi ya Kiswahili', 'Sports & Recreation'], ARRAY['Sports Journalism'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS2012', ARRAY['Biology', 'Literature in English', 'Sports & Recreation'], ARRAY['Sports Psychology'], 4.0, 'HIGH'),
((SELECT id FROM track), 'AS2025', ARRAY['General Science', 'German', 'Sports & Recreation'], ARRAY['International Sports'], 3.9, 'LOW'),
((SELECT id FROM track), 'AS2010', ARRAY['Biology', 'German', 'Sports & Recreation'], ARRAY['International Sports'], 3.9, 'LOW'),
((SELECT id FROM track), 'AS2008', ARRAY['Biology', 'French', 'Sports & Recreation'], ARRAY['International Sports'], 3.9, 'LOW'),
((SELECT id FROM track), 'AS2015', ARRAY['Biology', 'Media Technology', 'Sports & Recreation'], ARRAY['Sports Media'], 4.1, 'HIGH'),
((SELECT id FROM track), 'AS2019', ARRAY['Christian Religious Education', 'General Science', 'Sports & Recreation'], ARRAY['Sports Coaching'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2004', ARRAY['Biology', 'Christian Religious Education', 'Sports & Recreation'], ARRAY['Sports Coaching'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS2022', ARRAY['Fasihi ya Kiswahili', 'General Science', 'Sports & Recreation'], ARRAY['Sports Commentary'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS2023', ARRAY['French', 'General Science', 'Sports & Recreation'], ARRAY['International Sports'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS2016', ARRAY['Arabic', 'General Science', 'Sports & Recreation'], ARRAY['International Sports'], 3.8, 'LOW')
ON CONFLICT (code) DO NOTHING;

-- 2. ARTS & SPORTS SCIENCE > ARTS
WITH track AS (SELECT id FROM tracks WHERE code = 'ARTS_T')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'AS1021', ARRAY['Computer Studies', 'Fine Arts', 'Music & Dance'], ARRAY['Digital Art', 'Multimedia'], 4.0, 'HIGH'),
((SELECT id FROM track), 'AS1049', ARRAY['Literature in English', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts', 'Drama'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'AS1027', ARRAY['Fine Arts', 'General Science', 'Music & Dance'], ARRAY['Art Conservation', 'Acoustics'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1038', ARRAY['Business Studies', 'Music & Dance', 'Theatre & Film'], ARRAY['Arts Administration', 'Entertainment Management'], 4.1, 'HIGH'),
((SELECT id FROM track), 'AS1007', ARRAY['Fine Arts', 'Hindu Religious Education', 'Theatre & Film'], ARRAY['Creative Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1042', ARRAY['Hindu Religious Education', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1002', ARRAY['Biology', 'Fine Arts', 'Theatre & Film'], ARRAY['Medical Illustration'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'AS1036', ARRAY['Arabic', 'Music & Dance', 'Theatre & Film'], ARRAY['Cultural Arts'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS1005', ARRAY['Christian Religious Education', 'Fine Arts', 'Theatre & Film'], ARRAY['Creative Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1048', ARRAY['History & Citizenship', 'Music & Dance', 'Theatre & Film'], ARRAY['Art History', 'Cultural Heritage'], 3.7, 'MEDIUM'),
((SELECT id FROM track), 'AS1001', ARRAY['Arabic', 'Fine Arts', 'Theatre & Film'], ARRAY['Cultural Arts'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS1012', ARRAY['Fine Arts', 'German', 'Theatre & Film'], ARRAY['International Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1043', ARRAY['Fasihi ya Kiswahili', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS1032', ARRAY['Fine Arts', 'Mandarine Chinese', 'Music & Dance'], ARRAY['International Arts'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS1044', ARRAY['French', 'Music & Dance', 'Theatre & Film'], ARRAY['International Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1029', ARRAY['Fine Arts', 'German', 'Music & Dance'], ARRAY['International Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1009', ARRAY['Fine Arts', 'French', 'Theatre & Film'], ARRAY['International Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1022', ARRAY['Christian Religious Education', 'Fine Arts', 'Music & Dance'], ARRAY['Creative Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1019', ARRAY['Biology', 'Fine Arts', 'Music & Dance'], ARRAY['Art Therapy', 'Music Therapy'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'AS1011', ARRAY['Fine Arts', 'Geography', 'Theatre & Film'], ARRAY['Set Design', 'Location Scouting'], 3.8, 'MEDIUM'),
((SELECT id FROM track), 'AS1030', ARRAY['Fine Arts', 'History & Citizenship', 'Music & Dance'], ARRAY['Art History'], 3.7, 'LOW'),
((SELECT id FROM track), 'AS1039', ARRAY['Computer Studies', 'Music & Dance', 'Theatre & Film'], ARRAY['Sound Engineering', 'Editing'], 4.2, 'HIGH'),
((SELECT id FROM track), 'AS1018', ARRAY['Arabic', 'Fine Arts', 'Music & Dance'], ARRAY['Cultural Arts'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS1023', ARRAY['Fine Arts', 'Islamic Religious Education', 'Music & Dance'], ARRAY['Creative Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1037', ARRAY['Biology', 'Music & Dance', 'Theatre & Film'], ARRAY['Voice Science'], 4.0, 'LOW'),
((SELECT id FROM track), 'AS1047', ARRAY['German', 'Music & Dance', 'Theatre & Film'], ARRAY['International Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1040', ARRAY['Christian Religious Education', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1024', ARRAY['Fine Arts', 'Hindu Religious Education', 'Music & Dance'], ARRAY['Creative Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1050', ARRAY['Mandarine Chinese', 'Music & Dance', 'Theatre & Film'], ARRAY['International Arts'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS1015', ARRAY['Fine Arts', 'Mandarine Chinese', 'Theatre & Film'], ARRAY['International Arts'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS1026', ARRAY['Fine Arts', 'French', 'Music & Dance'], ARRAY['International Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1045', ARRAY['General Science', 'Music & Dance', 'Theatre & Film'], ARRAY['Technical Arts'], 3.7, 'LOW'),
((SELECT id FROM track), 'AS1003', ARRAY['Business Studies', 'Fine Arts', 'Theatre & Film'], ARRAY['Art Direction', 'Production'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'AS1016', ARRAY['Core Mathematics', 'Fine Arts', 'Theatre & Film'], ARRAY['Architecture', 'Animation'], 4.3, 'HIGH'),
((SELECT id FROM track), 'AS1017', ARRAY['Fine Arts', 'Sports & Recreation', 'Theatre & Film'], ARRAY['Stunt Coordination'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'AS1010', ARRAY['Fine Arts', 'General Science', 'Theatre & Film'], ARRAY['Visual Effects'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'AS1046', ARRAY['Geography', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts'], 3.7, 'LOW'),
((SELECT id FROM track), 'AS1028', ARRAY['Fine Arts', 'Geography', 'Music & Dance'], ARRAY['Creative Arts'], 3.7, 'LOW'),
((SELECT id FROM track), 'AS1051', ARRAY['Core Mathematics', 'Music & Dance', 'Theatre & Film'], ARRAY['Audio Engineering'], 4.2, 'HIGH'),
((SELECT id FROM track), 'AS1052', ARRAY['Music & Dance', 'Sports & Recreation', 'Theatre & Film'], ARRAY['Dance Performance'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS1008', ARRAY['Fasihi ya Kiswahili', 'Fine Arts', 'Theatre & Film'], ARRAY['Creative Arts'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS1020', ARRAY['Business Studies', 'Fine Arts', 'Music & Dance'], ARRAY['Art Dealership'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS1004', ARRAY['Computer Studies', 'Fine Arts', 'Theatre & Film'], ARRAY['Digital Animation'], 4.3, 'HIGH'),
((SELECT id FROM track), 'AS1014', ARRAY['Fine Arts', 'Literature in English', 'Theatre & Film'], ARRAY['Screenwriting'], 4.0, 'HIGH'),
((SELECT id FROM track), 'AS1041', ARRAY['Islamic Religious Education', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1013', ARRAY['Fine Arts', 'History & Citizenship', 'Theatre & Film'], ARRAY['Costume Design'], 3.7, 'MEDIUM'),
((SELECT id FROM track), 'AS1034', ARRAY['Fine Arts', 'Music & Dance', 'Sports & Recreation'], ARRAY['Creative Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'AS1035', ARRAY['Fine Arts', 'Music & Dance', 'Theatre & Film'], ARRAY['Performing Arts'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'AS1006', ARRAY['Fine Arts', 'Islamic Religious Education', 'Theatre & Film'], ARRAY['Creative Arts'], 3.5, 'LOW'),
((SELECT id FROM track), 'AS1025', ARRAY['Fasihi ya Kiswahili', 'Fine Arts', 'Music & Dance'], ARRAY['Creative Arts'], 3.6, 'LOW'),
((SELECT id FROM track), 'AS1031', ARRAY['Fine Arts', 'Literature in English', 'Music & Dance'], ARRAY['Creative Arts'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'AS1033', ARRAY['Core Mathematics', 'Fine Arts', 'Music & Dance'], ARRAY['Acoustic Engineering'], 4.2, 'MEDIUM')
ON CONFLICT (code) DO NOTHING;

-- 3. SOCIAL SCIENCES > LANGUAGES & LITERATURE
WITH track AS (SELECT id FROM tracks WHERE code = 'LANG_LIT')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'SS1006', ARRAY['Arabic', 'Computer Studies', 'French'], ARRAY['Computational Linguistics'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS1040', ARRAY['Computer Studies', 'Fasihi ya Kiswahili', 'Indigenous Language'], ARRAY['Localization'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS1060', ARRAY['General Science', 'Indigenous Language', 'Literature in English'], ARRAY['Linguistics'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1059', ARRAY['Arabic', 'Christian Religious Education', 'Kenya Sign Language'], ARRAY['Translation'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1037', ARRAY['Fasihi ya Kiswahili', 'General Science', 'Kenya Sign Language'], ARRAY['Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1084', ARRAY['Core Mathematics', 'French', 'Mandarine Chinese'], ARRAY['International Business', 'Cryptography'], 4.5, 'HIGH'),
((SELECT id FROM track), 'SS1044', ARRAY['Core Mathematics', 'Fasihi ya Kiswahili', 'Kenya Sign Language'], ARRAY['Linguistics'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1014', ARRAY['Arabic', 'French', 'General Science'], ARRAY['Translation'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1065', ARRAY['German', 'Indigenous Language', 'Literature in English'], ARRAY['Translation'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1001', ARRAY['French', 'Indigenous Language', 'Literature in English'], ARRAY['Translation'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1002', ARRAY['Fasihi ya Kiswahili', 'Indigenous Language', 'Literature in English'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1058', ARRAY['Arabic', 'Computer Studies', 'Kenya Sign Language'], ARRAY['Assistive Technology'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS1043', ARRAY['Arabic', 'Fasihi ya Kiswahili', 'Indigenous Language'], ARRAY['Translation'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1011', ARRAY['Arabic', 'French', 'Hindu Religious Education'], ARRAY['Translation'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1018', ARRAY['Fasihi ya Kiswahili', 'Indigenous Language', 'Kenya Sign Language'], ARRAY['Special Education'], 3.6, 'MEDIUM'),
((SELECT id FROM track), 'SS1019', ARRAY['Core Mathematics', 'Arabic', 'French'], ARRAY['International Relations'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'SS1029', ARRAY['Fasihi ya Kiswahili', 'General Science', 'Indigenous Language'], ARRAY['Education'], 3.5, 'LOW'),
((SELECT id FROM track), 'SS1050', ARRAY['French', 'German', 'Islamic Religious Education'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1064', ARRAY['Arabic', 'French', 'Kenya Sign Language'], ARRAY['Translation'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1074', ARRAY['Core Mathematics', 'Arabic', 'Kenya Sign Language'], ARRAY['Linguistics'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1033', ARRAY['Fasihi ya Kiswahili', 'Hindu Religious Education', 'Kenya Sign Language'], ARRAY['Special Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1025', ARRAY['Fasihi ya Kiswahili', 'German', 'Indigenous Language'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1036', ARRAY['Fasihi ya Kiswahili', 'Hindu Religious Education', 'Indigenous Language'], ARRAY['Education'], 3.5, 'LOW'),
((SELECT id FROM track), 'SS1022', ARRAY['Fasihi ya Kiswahili', 'Indigenous Language', 'Mandarine Chinese'], ARRAY['International Relations'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1020', ARRAY['Core Mathematics', 'Fasihi ya Kiswahili', 'Indigenous Language'], ARRAY['Linguistics'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS1055', ARRAY['French', 'Geography', 'Mandarine Chinese'], ARRAY['International Relations'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS1007', ARRAY['Indigenous Language', 'Islamic Religious Education', 'Literature in English'], ARRAY['Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1026', ARRAY['Fasihi ya Kiswahili', 'Kenya Sign Language', 'Mandarine Chinese'], ARRAY['Translation'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1069', ARRAY['Core Mathematics', 'Indigenous Language', 'Literature in English'], ARRAY['Linguistics'], 4.0, 'LOW'),
((SELECT id FROM track), 'SS1031', ARRAY['Fasihi ya Kiswahili', 'Islamic Religious Education', 'Kenya Sign Language'], ARRAY['Special Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1077', ARRAY['Christian Religious Education', 'French', 'Mandarine Chinese'], ARRAY['International Relations'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1057', ARRAY['Arabic', 'Business Studies', 'Kenya Sign Language'], ARRAY['Business Interpretation'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS1046', ARRAY['Core Mathematics', 'French', 'German'], ARRAY['International Business'], 4.3, 'HIGH'),
((SELECT id FROM track), 'SS1023', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'Kenya Sign Language'], ARRAY['Social Work'], 3.8, 'MEDIUM'),
((SELECT id FROM track), 'SS1080', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'Literature in English'], ARRAY['Publishing', 'Journalism'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS1038', ARRAY['Fasihi ya Kiswahili', 'Indigenous Language', 'Islamic Religious Education'], ARRAY['Education'], 3.5, 'LOW'),
((SELECT id FROM track), 'SS1051', ARRAY['French', 'Geography', 'German'], ARRAY['International Relations'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS1030', ARRAY['Christian Religious Education', 'Fasihi ya Kiswahili', 'Kenya Sign Language'], ARRAY['Special Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1068', ARRAY['Indigenous Language', 'Literature in English', 'Mandarine Chinese'], ARRAY['Translation'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'SS1070', ARRAY['Arabic', 'Geography', 'Kenya Sign Language'], ARRAY['Social Work'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1041', ARRAY['Fasihi ya Kiswahili', 'History & Citizenship', 'Kenya Sign Language'], ARRAY['Special Education'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1039', ARRAY['Fasihi ya Kiswahili', 'Geography', 'Kenya Sign Language'], ARRAY['Social Work'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1079', ARRAY['French', 'Hindu Religious Education', 'Mandarine Chinese'], ARRAY['International Relations'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1049', ARRAY['French', 'German', 'History & Citizenship'], ARRAY['International Law'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS1047', ARRAY['Computer Studies', 'French', 'German'], ARRAY['Computational Linguistics'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS1067', ARRAY['History & Citizenship', 'Indigenous Language', 'Literature in English'], ARRAY['Cultural Heritage'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1009', ARRAY['Arabic', 'French', 'Islamic Religious Education'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1078', ARRAY['French', 'Islamic Religious Education', 'Mandarine Chinese'], ARRAY['International Relations'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1034', ARRAY['Christian Religious Education', 'Fasihi ya Kiswahili', 'Indigenous Language'], ARRAY['Education'], 3.5, 'LOW'),
((SELECT id FROM track), 'SS1071', ARRAY['Indigenous Language', 'Kenya Sign Language', 'Literature in English'], ARRAY['Special Education'], 3.7, 'MEDIUM'),
((SELECT id FROM track), 'SS1017', ARRAY['Arabic', 'French', 'Mandarine Chinese'], ARRAY['Diplomacy'], 4.3, 'HIGH'),
((SELECT id FROM track), 'SS1075', ARRAY['Business Studies', 'French', 'Mandarine Chinese'], ARRAY['International Business'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS1052', ARRAY['French', 'German', 'Hindu Religious Education'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1016', ARRAY['Arabic', 'French', 'History & Citizenship'], ARRAY['International Relations'], 3.8, 'MEDIUM'),
((SELECT id FROM track), 'SS1032', ARRAY['Fasihi ya Kiswahili', 'French', 'Indigenous Language'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1005', ARRAY['Hindu Religious Education', 'Indigenous Language', 'Literature in English'], ARRAY['Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1082', ARRAY['Fasihi ya Kiswahili', 'Literature in English', 'Mandarine Chinese'], ARRAY['Translation'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'SS1062', ARRAY['Arabic', 'Islamic Religious Education', 'Kenya Sign Language'], ARRAY['Social Work'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1076', ARRAY['Computer Studies', 'French', 'Mandarine Chinese'], ARRAY['Tech Support International'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS1066', ARRAY['Arabic', 'General Science', 'Kenya Sign Language'], ARRAY['Social Work'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1083', ARRAY['Fasihi ya Kiswahili', 'Kenya Sign Language', 'Literature in English'], ARRAY['Special Education'], 3.8, 'MEDIUM'),
((SELECT id FROM track), 'SS1045', ARRAY['Business Studies', 'French', 'German'], ARRAY['International Trade'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS1042', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'Indigenous Language'], ARRAY['Administration'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1028', ARRAY['Computer Studies', 'Fasihi ya Kiswahili', 'Kenya Sign Language'], ARRAY['Assistive Technology'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS1024', ARRAY['Fasihi ya Kiswahili', 'History & Citizenship', 'Indigenous Language'], ARRAY['Cultural Studies'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1081', ARRAY['Fasihi ya Kiswahili', 'History & Citizenship', 'Literature in English'], ARRAY['Law', 'Journalism'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS1056', ARRAY['French', 'History & Citizenship', 'Mandarine Chinese'], ARRAY['Diplomacy'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS1072', ARRAY['Arabic', 'History & Citizenship', 'Kenya Sign Language'], ARRAY['Social Work'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1004', ARRAY['Arabic', 'Business Studies', 'French'], ARRAY['International Business'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS1061', ARRAY['Geography', 'Indigenous Language', 'Literature in English'], ARRAY['Cultural Studies'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1015', ARRAY['Arabic', 'French', 'Geography'], ARRAY['International Relations'], 3.8, 'MEDIUM'),
((SELECT id FROM track), 'SS1054', ARRAY['French', 'General Science', 'Mandarine Chinese'], ARRAY['International Relations'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1035', ARRAY['Fasihi ya Kiswahili', 'French', 'Kenya Sign Language'], ARRAY['Translation'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1021', ARRAY['Arabic', 'Fasihi ya Kiswahili', 'Kenya Sign Language'], ARRAY['Social Work'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1012', ARRAY['Business Studies', 'Indigenous Language', 'Literature in English'], ARRAY['Publishing'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1063', ARRAY['Arabic', 'Hindu Religious Education', 'Kenya Sign Language'], ARRAY['Social Work'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1053', ARRAY['French', 'General Science', 'German'], ARRAY['Translation'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS1010', ARRAY['Computer Studies', 'Indigenous Language', 'Literature in English'], ARRAY['Digital Publishing'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS1048', ARRAY['Christian Religious Education', 'French', 'German'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1027', ARRAY['Fasihi ya Kiswahili', 'Geography', 'Indigenous Language'], ARRAY['Cultural Studies'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1003', ARRAY['Christian Religious Education', 'Indigenous Language', 'Literature in English'], ARRAY['Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS1073', ARRAY['Arabic', 'Kenya Sign Language', 'Mandarine Chinese'], ARRAY['Translation'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS1013', ARRAY['Arabic', 'Indigenous Language', 'Literature in English'], ARRAY['Translation'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS1008', ARRAY['Arabic', 'Christian Religious Education', 'French'], ARRAY['Translation'], 3.7, 'LOW')
ON CONFLICT (code) DO NOTHING;

-- 4. STEM > APPLIED SCIENCES
WITH track AS (SELECT id FROM tracks WHERE code = 'APP_SCI')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'ST2007', ARRAY['Business Studies', 'Computer Studies', 'Physics'], ARRAY['Tech Entrepreneurship'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2045', ARRAY['Agriculture', 'Building & Construction', 'Business Studies'], ARRAY['Agribusiness'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2070', ARRAY['Agriculture', 'Aviation', 'Geography'], ARRAY['Aerial Surveying'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST2067', ARRAY['Agriculture', 'Computer Studies', 'Physics'], ARRAY['Agri-Tech'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2091', ARRAY['Core Mathematics', 'Agriculture', 'Home Science'], ARRAY['Food Science'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2075', ARRAY['Agriculture', 'Geography', 'Physics'], ARRAY['Geophysics'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2019', ARRAY['Computer Studies', 'Home Science', 'Wood Work'], ARRAY['Interior Design'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2048', ARRAY['Agriculture', 'Business Studies', 'Electricity'], ARRAY['Agri-Engineering'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2049', ARRAY['Agriculture', 'Business Studies', 'General Science'], ARRAY['Agribusiness'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST2058', ARRAY['Agriculture', 'Building & Construction', 'Computer Studies'], ARRAY['Smart Farming'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2097', ARRAY['Biology', 'Business Studies', 'Computer Studies'], ARRAY['Health Informatics'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST2077', ARRAY['Core Mathematics', 'Business Studies', 'Computer Studies'], ARRAY['FinTech'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST2040', ARRAY['Core Mathematics', 'Biology', 'Geography'], ARRAY['Environmental Science'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2056', ARRAY['Agriculture', 'Aviation', 'Computer Studies'], ARRAY['Drone Agriculture'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST2096', ARRAY['Aviation', 'Business Studies', 'Computer Studies'], ARRAY['Aviation Management'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST2059', ARRAY['Agriculture', 'Chemistry', 'Computer Studies'], ARRAY['Agri-Tech'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2020', ARRAY['Aviation', 'Computer Studies', 'Home Science'], ARRAY['Cabin Crew Mgmt'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2092', ARRAY['Agriculture', 'Home Science', 'Metal Work'], ARRAY['Food Processing eqp'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST2017', ARRAY['Computer Studies', 'Geography', 'Metal Work'], ARRAY['GIS Fabrication'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2083', ARRAY['Agriculture', 'Building & Construction', 'Home Science'], ARRAY['Landscape Design'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'ST2090', ARRAY['Agriculture', 'Home Science', 'Marine & Fisheries'], ARRAY['Aquaculture'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2024', ARRAY['Chemistry', 'Computer Studies', 'Home Science'], ARRAY['Food Technology'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2095', ARRAY['Agriculture', 'Home Science', 'Wood Work'], ARRAY['Cottage Industry'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST2060', ARRAY['Agriculture', 'Computer Studies', 'Electricity'], ARRAY['Automated Farming'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2009', ARRAY['Business Studies', 'Computer Studies', 'Wood Work'], ARRAY['Furniture Business'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'ST2047', ARRAY['Agriculture', 'Business Studies', 'Computer Studies'], ARRAY['E-Agribusiness'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2098', ARRAY['Building & Construction', 'Business Studies', 'Computer Studies'], ARRAY['Real Estate Tech'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2043', ARRAY['Agriculture', 'Aviation', 'Business Studies'], ARRAY['Aerial Logistics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2028', ARRAY['Computer Studies', 'Home Science', 'Marine & Fisheries'], ARRAY['Seafood Logistics'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2078', ARRAY['Agriculture', 'Geography', 'Wood Work'], ARRAY['Forestry'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2010', ARRAY['Aviation', 'Computer Studies', 'Geography'], ARRAY['Flight Planning'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2055', ARRAY['Agriculture', 'Business Studies', 'Wood Work'], ARRAY['Timber Business'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'ST2001', ARRAY['Business Studies', 'Computer Studies', 'Electricity'], ARRAY['Tech Hardware Biz'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2025', ARRAY['Computer Studies', 'Electricity', 'Home Science'], ARRAY['Smart Home Tech'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2093', ARRAY['Agriculture', 'Home Science', 'Physics'], ARRAY['Food Engineering'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2069', ARRAY['Agriculture', 'Computer Studies', 'Wood Work'], ARRAY['Precision Forestry'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2076', ARRAY['Agriculture', 'Geography', 'Power Mechanics'], ARRAY['Agricultural Mech'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2053', ARRAY['Agriculture', 'Business Studies', 'Physics'], ARRAY['Agri-Physics'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2063', ARRAY['Agriculture', 'Computer Studies', 'Home Science'], ARRAY['Nutritional Data'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2004', ARRAY['Business Studies', 'Computer Studies', 'Marine & Fisheries'], ARRAY['Blue Economy Tech'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2085', ARRAY['Agriculture', 'Business Studies', 'Home Science'], ARRAY['Catering Business'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST2030', ARRAY['Computer Studies', 'Home Science', 'Metal Work'], ARRAY['Kitchen Equip Design'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2046', ARRAY['Agriculture', 'Business Studies', 'Chemistry'], ARRAY['Agro-Chemical Biz'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2051', ARRAY['Agriculture', 'Business Studies', 'Marine & Fisheries'], ARRAY['Aquaculture Biz'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2087', ARRAY['Agriculture', 'Electricity', 'Home Science'], ARRAY['Food Processing'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2015', ARRAY['Computer Studies', 'Geography', 'Marine & Fisheries'], ARRAY['Oceanography'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2081', ARRAY['Agriculture', 'Biology', 'Home Science'], ARRAY['Nutrition'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2066', ARRAY['Agriculture', 'Computer Studies', 'Metal Work'], ARRAY['Agri-Fabrication'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2014', ARRAY['Computer Studies', 'General Science', 'Geography'], ARRAY['Geospatial Analysis'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2011', ARRAY['Biology', 'Computer Studies', 'Geography'], ARRAY['Ecology Modeling'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2052', ARRAY['Agriculture', 'Business Studies', 'Metal Work'], ARRAY['Farm Machinery Biz'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2086', ARRAY['Agriculture', 'Chemistry', 'Home Science'], ARRAY['Food Chemistry'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2089', ARRAY['Agriculture', 'Geography', 'Home Science'], ARRAY['Food Security'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2065', ARRAY['Core Mathematics', 'Agriculture', 'Computer Studies'], ARRAY['Agri-Data Science'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2038', ARRAY['Core Mathematics', 'Biology', 'Computer Studies'], ARRAY['Bioinformatics'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST2018', ARRAY['Computer Studies', 'Geography', 'Physics'], ARRAY['Remote Sensing'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST2064', ARRAY['Agriculture', 'Computer Studies', 'Marine & Fisheries'], ARRAY['Precision Aqua'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2071', ARRAY['Agriculture', 'Biology', 'Geography'], ARRAY['Ecology'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2012', ARRAY['Building & Construction', 'Computer Studies', 'Geography'], ARRAY['Urban Planning'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2062', ARRAY['Agriculture', 'Computer Studies', 'Geography'], ARRAY['GIS Agriculture'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2080', ARRAY['Agriculture', 'Electricity', 'Geography'], ARRAY['Rural Electrification'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2039', ARRAY['Core Mathematics', 'Biology', 'Electricity'], ARRAY['Biomedical Eng'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST2023', ARRAY['Business Studies', 'Computer Studies', 'Home Science'], ARRAY['Hospitality Mgmt'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2006', ARRAY['Business Studies', 'Computer Studies', 'Metal Work'], ARRAY['Industrial Fabrication'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2094', ARRAY['Agriculture', 'Home Science', 'Power Mechanics'], ARRAY['Backyard Mech'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST2016', ARRAY['Core Mathematics', 'Computer Studies', 'Geography'], ARRAY['Geospatial Data'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST2031', ARRAY['Computer Studies', 'Home Science', 'Physics'], ARRAY['Energy Efficiency'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST2013', ARRAY['Chemistry', 'Computer Studies', 'Geography'], ARRAY['Geochemistry'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2084', ARRAY['Agriculture', 'Geography', 'Marine & Fisheries'], ARRAY['Coastal Agriculture'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2088', ARRAY['Agriculture', 'General Science', 'Home Science'], ARRAY['Community Nutrition'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST2002', ARRAY['Business Studies', 'Computer Studies', 'General Science'], ARRAY['IT Support'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2032', ARRAY['Computer Studies', 'Home Science', 'Power Mechanics'], ARRAY['Appliance Repair'], 4.0, 'LOW'),
((SELECT id FROM track), 'ST2054', ARRAY['Agriculture', 'Business Studies', 'Power Mechanics'], ARRAY['Agri-Mechanics Biz'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST2079', ARRAY['Agriculture', 'Aviation', 'Home Science'], ARRAY['Flight Catering'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST2044', ARRAY['Agriculture', 'Biology', 'Business Studies'], ARRAY['Agribusiness'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2003', ARRAY['Business Studies', 'Computer Studies', 'Geography'], ARRAY['Logistics Tech'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST2041', ARRAY['Core Mathematics', 'Biology', 'Home Science'], ARRAY['Dietetics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2057', ARRAY['Agriculture', 'Biology', 'Computer Studies'], ARRAY['Bio-Agri Tech'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST2082', ARRAY['Agriculture', 'General Science', 'Geography'], ARRAY['Land Surveying'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST2068', ARRAY['Agriculture', 'Computer Studies', 'Power Mechanics'], ARRAY['Automated Mach'], 4.3, 'HIGH')
ON CONFLICT (code) DO NOTHING;

-- 5. STEM > PURE SCIENCES
WITH track AS (SELECT id FROM tracks WHERE code = 'PURE_SCI')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'ST1044', ARRAY['Biology', 'Building & Construction', 'Chemistry'], ARRAY['Construction Science'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST1042', ARRAY['Agriculture', 'Biology', 'Chemistry'], ARRAY['Agricultural Science'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST1026', ARRAY['Core Mathematics', 'Business Studies', 'General Science'], ARRAY['Actuarial Science'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1035', ARRAY['Core Mathematics', 'Electricity', 'Physics'], ARRAY['Electrical Eng'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST1005', ARRAY['Core Mathematics', 'Biology', 'Building & Construction'], ARRAY['Architecture'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST1039', ARRAY['Core Mathematics', 'Metal Work', 'Physics'], ARRAY['Metallurgy'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1016', ARRAY['Core Mathematics', 'Chemistry', 'Geography'], ARRAY['Geology'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1043', ARRAY['Aviation', 'Biology', 'Chemistry'], ARRAY['Aerospace Science'], 4.7, 'HIGH'),
((SELECT id FROM track), 'ST1022', ARRAY['Core Mathematics', 'Chemistry', 'Wood Work'], ARRAY['Material Science'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST1008', ARRAY['Core Mathematics', 'Biology', 'Power Mechanics'], ARRAY['Biomechanics'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1018', ARRAY['Core Mathematics', 'Chemistry', 'Marine & Fisheries'], ARRAY['Marine Biology'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST1015', ARRAY['Core Mathematics', 'Chemistry', 'Electricity'], ARRAY['Chemical Eng'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST1007', ARRAY['Core Mathematics', 'Biology', 'Physics'], ARRAY['Biophysics'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1024', ARRAY['Core Mathematics', 'Aviation', 'General Science'], ARRAY['Aviation Tech'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST1034', ARRAY['Core Mathematics', 'Computer Studies', 'Physics'], ARRAY['Computational Physics'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST1023', ARRAY['Core Mathematics', 'Agriculture', 'General Science'], ARRAY['Agri-Science'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST1033', ARRAY['Core Mathematics', 'Business Studies', 'Physics'], ARRAY['Financial Eng'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST1010', ARRAY['Core Mathematics', 'Agriculture', 'Chemistry'], ARRAY['Soil Science'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST1006', ARRAY['Core Mathematics', 'Biology', 'Metal Work'], ARRAY['Bio-Materials'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1011', ARRAY['Core Mathematics', 'Aviation', 'Chemistry'], ARRAY['Aviation Fuel Sci'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1004', ARRAY['Core Mathematics', 'Biology', 'Chemistry'], ARRAY['Medicine', 'Pharmacy'], 4.8, 'HIGH'),
((SELECT id FROM track), 'ST1038', ARRAY['Core Mathematics', 'Marine & Fisheries', 'Physics'], ARRAY['Ocean Engineering'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST1041', ARRAY['Core Mathematics', 'Physics', 'Wood Work'], ARRAY['Structural Eng'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1031', ARRAY['Core Mathematics', 'Aviation', 'Physics'], ARRAY['Aeronautics'], 4.7, 'HIGH'),
((SELECT id FROM track), 'ST1047', ARRAY['Core Mathematics', 'Biology', 'Marine & Fisheries'], ARRAY['Marine Studies'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1009', ARRAY['Core Mathematics', 'Biology', 'Wood Work'], ARRAY['Bio-Structures'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST1028', ARRAY['Core Mathematics', 'General Science', 'Geography'], ARRAY['Earth Science'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST1030', ARRAY['Core Mathematics', 'Agriculture', 'Physics'], ARRAY['Agri-Physics'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1045', ARRAY['Biology', 'Business Studies', 'Chemistry'], ARRAY['Pharma Business'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST1012', ARRAY['Core Mathematics', 'Building & Construction', 'Chemistry'], ARRAY['Construction Mat'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST1014', ARRAY['Core Mathematics', 'Chemistry', 'Computer Studies'], ARRAY['Computational Chem'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1002', ARRAY['Core Mathematics', 'Aviation', 'Biology'], ARRAY['Space Medicine'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST1001', ARRAY['Core Mathematics', 'Agriculture', 'Biology'], ARRAY['Genetics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST1021', ARRAY['Core Mathematics', 'Chemistry', 'Power Mechanics'], ARRAY['Chemical Mech'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST1046', ARRAY['Biology', 'Chemistry', 'Computer Studies'], ARRAY['Bioinformatics'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST1019', ARRAY['Core Mathematics', 'Chemistry', 'Metal Work'], ARRAY['Metallurgy'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1040', ARRAY['Core Mathematics', 'Physics', 'Power Mechanics'], ARRAY['Mechanical Eng'], 4.6, 'HIGH'),
((SELECT id FROM track), 'ST1032', ARRAY['Core Mathematics', 'Building & Construction', 'Physics'], ARRAY['Civil Engineering'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1013', ARRAY['Core Mathematics', 'Business Studies', 'Chemistry'], ARRAY['Industrial Chem'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST1036', ARRAY['Core Mathematics', 'Geography', 'Physics'], ARRAY['Geophysics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST1017', ARRAY['Core Mathematics', 'Chemistry', 'Home Science'], ARRAY['Food Science'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1037', ARRAY['Core Mathematics', 'Home Science', 'Physics'], ARRAY['Textile Eng'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST1029', ARRAY['Core Mathematics', 'General Science', 'Home Science'], ARRAY['Nutrition'], 4.0, 'LOW'),
((SELECT id FROM track), 'ST1027', ARRAY['Core Mathematics', 'Computer Studies', 'General Science'], ARRAY['Data Anal'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST1025', ARRAY['Core Mathematics', 'Building & Construction', 'General Science'], ARRAY['Construction'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST1020', ARRAY['Core Mathematics', 'Chemistry', 'Physics'], ARRAY['Physics'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST1003', ARRAY['Core Mathematics', 'Biology', 'Business Studies'], ARRAY['Health Admin'], 4.2, 'MEDIUM')
ON CONFLICT (code) DO NOTHING;

-- 6. STEM > TECHNICAL STUDIES
WITH track AS (SELECT id FROM tracks WHERE code = 'TECH')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'ST3050', ARRAY['General Science', 'Marine & Fisheries', 'Media Technology'], ARRAY['Marine Media'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3121', ARRAY['Aviation', 'Geography', 'Physics'], ARRAY['Aviation Nav'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST3074', ARRAY['Computer Studies', 'General Science', 'Media Technology'], ARRAY['Multimedia Tech'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST3084', ARRAY['Biology', 'Business Studies', 'Metal Work'], ARRAY['Biomedical Fab'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3105', ARRAY['Geography', 'Metal Work', 'Physics'], ARRAY['Mining Tech'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST3013', ARRAY['Biology', 'Geography', 'Power Mechanics'], ARRAY['Environmental Eng'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3008', ARRAY['Electricity', 'General Science', 'Home Science'], ARRAY['Appliance Tech'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3118', ARRAY['General Science', 'Marine & Fisheries', 'Power Mechanics'], ARRAY['Marine Engine'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST3047', ARRAY['Core Mathematics', 'General Science', 'Marine & Fisheries'], ARRAY['Marine Science'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3015', ARRAY['Chemistry', 'Geography', 'Power Mechanics'], ARRAY['Petroleum Eng'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST3068', ARRAY['Business Studies', 'Geography', 'Media Technology'], ARRAY['Geo-Media'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3065', ARRAY['Biology', 'Business Studies', 'Media Technology'], ARRAY['Health Media'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3089', ARRAY['Business Studies', 'Marine & Fisheries', 'Metal Work'], ARRAY['Shipbuilding Biz'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3120', ARRAY['Aviation', 'Geography', 'Media Technology'], ARRAY['Aerial Photo'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3091', ARRAY['Business Studies', 'Media Technology', 'Metal Work'], ARRAY['Fab Business'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3011', ARRAY['General Science', 'Media Technology', 'Power Mechanics'], ARRAY['Auto-Media'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3044', ARRAY['Computer Studies', 'General Science', 'Marine & Fisheries'], ARRAY['Marine Tech'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST3024', ARRAY['Core Mathematics', 'Electricity', 'Geography'], ARRAY['Power Grid Maps'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST3054', ARRAY['Chemistry', 'Geography', 'Marine & Fisheries'], ARRAY['Oceanography'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST3022', ARRAY['Electricity', 'Geography', 'Marine & Fisheries'], ARRAY['Underwater Elec'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST3053', ARRAY['General Science', 'Media Technology', 'Wood Work'], ARRAY['Set Construction'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3006', ARRAY['Computer Studies', 'Electricity', 'Geography'], ARRAY['GIS Power'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST3082', ARRAY['Geography', 'Media Technology', 'Physics'], ARRAY['Broadcast Eng'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST3038', ARRAY['Business Studies', 'Physics', 'Wood Work'], ARRAY['Carpentry Biz'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3107', ARRAY['Business Studies', 'Chemistry', 'Power Mechanics'], ARRAY['Auto-Chem Biz'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3081', ARRAY['Core Mathematics', 'Geography', 'Media Technology'], ARRAY['Geo-Informatics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3085', ARRAY['Business Studies', 'Chemistry', 'Metal Work'], ARRAY['Metallurgy Biz'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3018', ARRAY['Geography', 'Home Science', 'Power Mechanics'], ARRAY['Home Systems'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3034', ARRAY['Business Studies', 'Home Science', 'Wood Work'], ARRAY['Furniture Retail'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST3103', ARRAY['Core Mathematics', 'Geography', 'Metal Work'], ARRAY['Structural Fab'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3079', ARRAY['Computer Studies', 'Geography', 'Media Technology'], ARRAY['GIS Media'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3099', ARRAY['Chemistry', 'Geography', 'Metal Work'], ARRAY['Mining Chem'], 4.3, 'MEDIUM'),
((SELECT id FROM track), 'ST3017', ARRAY['Chemistry', 'Electricity', 'Geography'], ARRAY['Geothermal'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST3060', ARRAY['Geography', 'Home Science', 'Wood Work'], ARRAY['Interior Decor'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST3014', ARRAY['Biology', 'Electricity', 'Geography'], ARRAY['Bio-Energy'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3086', ARRAY['Business Studies', 'General Science', 'Metal Work'], ARRAY['Metal Trading'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'ST3016', ARRAY['Computer Studies', 'Geography', 'Power Mechanics'], ARRAY['GPS Tracking'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3083', ARRAY['Aviation', 'Business Studies', 'Metal Work'], ARRAY['Aircraft Maint'], 4.5, 'HIGH'),
((SELECT id FROM track), 'ST3046', ARRAY['General Science', 'Geography', 'Wood Work'], ARRAY['Forestry'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'ST3097', ARRAY['General Science', 'Media Technology', 'Metal Work'], ARRAY['Tech Art'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3032', ARRAY['Business Studies', 'Geography', 'Wood Work'], ARRAY['Timber Trade'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3061', ARRAY['Geography', 'Marine & Fisheries', 'Media Technology'], ARRAY['Undersea Media'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3104', ARRAY['Geography', 'Media Technology', 'Metal Work'], ARRAY['Industrial Design'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3027', ARRAY['Biology', 'Business Studies', 'Wood Work'], ARRAY['Bio-Materials Biz'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3051', ARRAY['Core Mathematics', 'General Science', 'Wood Work'], ARRAY['Wood Tech'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3035', ARRAY['Business Studies', 'Marine & Fisheries', 'Wood Work'], ARRAY['Boat Building Biz'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3090', ARRAY['Core Mathematics', 'Business Studies', 'Metal Work'], ARRAY['Fab Estimating'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3040', ARRAY['Core Mathematics', 'Business Studies', 'Marine & Fisheries'], ARRAY['Marine Logistics'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3071', ARRAY['Geography', 'Physics', 'Wood Work'], ARRAY['Wood Physics'], 4.0, 'LOW'),
((SELECT id FROM track), 'ST3059', ARRAY['Core Mathematics', 'Geography', 'Marine & Fisheries'], ARRAY['Hydrography'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3073', ARRAY['Business Studies', 'Media Technology', 'Physics'], ARRAY['Media Tech Biz'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST3031', ARRAY['Business Studies', 'General Science', 'Wood Work'], ARRAY['Wood Products'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST3029', ARRAY['Business Studies', 'Chemistry', 'Wood Work'], ARRAY['Wood Treatment'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3062', ARRAY['Geography', 'Marine & Fisheries', 'Physics'], ARRAY['Ocean Physics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3113', ARRAY['Core Mathematics', 'Business Studies', 'Power Mechanics'], ARRAY['Mechanic Biz'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3095', ARRAY['General Science', 'Marine & Fisheries', 'Metal Work'], ARRAY['Marine Welding'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3066', ARRAY['Business Studies', 'Chemistry', 'Media Technology'], ARRAY['Media Supply'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3096', ARRAY['Core Mathematics', 'General Science', 'Metal Work'], ARRAY['Metal Science'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3043', ARRAY['Computer Studies', 'General Science', 'Wood Work'], ARRAY['CNC Woodwork'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3023', ARRAY['Geography', 'Physics', 'Power Mechanics'], ARRAY['Geo-Engineering'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3078', ARRAY['Chemistry', 'Geography', 'Media Technology'], ARRAY['Sci-Comm'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3055', ARRAY['Biology', 'Geography', 'Wood Work'], ARRAY['Dendrology'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3094', ARRAY['General Science', 'Home Science', 'Metal Work'], ARRAY['Home Fittings'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST3067', ARRAY['Business Studies', 'Computer Studies', 'Media Technology'], ARRAY['Digital Media Biz'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST3020', ARRAY['Core Mathematics', 'Geography', 'Power Mechanics'], ARRAY['Transport Sys'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3042', ARRAY['Business Studies', 'Marine & Fisheries', 'Physics'], ARRAY['Marine Tech Sales'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3115', ARRAY['Business Studies', 'Physics', 'Power Mechanics'], ARRAY['Auto Physics'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3117', ARRAY['General Science', 'Home Science', 'Power Mechanics'], ARRAY['Appliance Mech'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3114', ARRAY['Business Studies', 'Media Technology', 'Power Mechanics'], ARRAY['Auto Media'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3110', ARRAY['Business Studies', 'Geography', 'Power Mechanics'], ARRAY['Logistics'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3063', ARRAY['Geography', 'Marine & Fisheries', 'Wood Work'], ARRAY['Boat Building'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3033', ARRAY['Business Studies', 'General Science', 'Marine & Fisheries'], ARRAY['Fisheries Biz'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3010', ARRAY['Core Mathematics', 'Electricity', 'General Science'], ARRAY['Basic Elec'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3026', ARRAY['Electricity', 'Geography', 'Physics'], ARRAY['Physics of Elec'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST3109', ARRAY['Business Studies', 'General Science', 'Power Mechanics'], ARRAY['Garage Mgmt'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3045', ARRAY['General Science', 'Home Science', 'Marine & Fisheries'], ARRAY['Seafood Prep'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3075', ARRAY['General Science', 'Home Science', 'Media Technology'], ARRAY['Home Media'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3106', ARRAY['Biology', 'Business Studies', 'Power Mechanics'], ARRAY['Bio-Mech Sales'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3101', ARRAY['Geography', 'Home Science', 'Metal Work'], ARRAY['Home Design'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3007', ARRAY['Electricity', 'Geography', 'Home Science'], ARRAY['Smart Homes'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3056', ARRAY['Chemistry', 'Geography', 'Wood Work'], ARRAY['Wood Chem'], 4.0, 'LOW'),
((SELECT id FROM track), 'ST3009', ARRAY['Electricity', 'General Science', 'Marine & Fisheries'], ARRAY['Marine Elec'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3080', ARRAY['Geography', 'Home Science', 'Media Technology'], ARRAY['Interior Design'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3057', ARRAY['Computer Studies', 'Geography', 'Wood Work'], ARRAY['Wood Design'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3112', ARRAY['Business Studies', 'Marine & Fisheries', 'Power Mechanics'], ARRAY['Marine Engine Biz'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3021', ARRAY['Geography', 'Media Technology', 'Power Mechanics'], ARRAY['Auto Design'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3058', ARRAY['Geography', 'Home Science', 'Marine & Fisheries'], ARRAY['Coastal Living'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3108', ARRAY['Business Studies', 'Computer Studies', 'Power Mechanics'], ARRAY['Auto Diagnostics'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST3048', ARRAY['General Science', 'Home Science', 'Wood Work'], ARRAY['Furniture'], 3.8, 'LOW'),
((SELECT id FROM track), 'ST3064', ARRAY['Core Mathematics', 'Geography', 'Wood Work'], ARRAY['Structural Wood'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3019', ARRAY['Geography', 'Marine & Fisheries', 'Power Mechanics'], ARRAY['Marine Eng'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3098', ARRAY['Biology', 'Geography', 'Metal Work'], ARRAY['Env Fabrication'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3049', ARRAY['General Science', 'Marine & Fisheries', 'Wood Work'], ARRAY['Marine Construction'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3092', ARRAY['Business Studies', 'Metal Work', 'Physics'], ARRAY['Metal Physics'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3025', ARRAY['Electricity', 'Geography', 'Media Technology'], ARRAY['Telecomm'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3087', ARRAY['Business Studies', 'Geography', 'Metal Work'], ARRAY['Metal Logistics'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3088', ARRAY['Business Studies', 'Home Science', 'Metal Work'], ARRAY['Homeware Biz'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3041', ARRAY['Business Studies', 'Marine & Fisheries', 'Media Technology'], ARRAY['Marine Media Biz'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3102', ARRAY['Geography', 'Marine & Fisheries', 'Metal Work'], ARRAY['Rig Construction'], 4.4, 'HIGH'),
((SELECT id FROM track), 'ST3072', ARRAY['Core Mathematics', 'Business Studies', 'Media Technology'], ARRAY['Media Mgmt'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST3100', ARRAY['General Science', 'Geography', 'Metal Work'], ARRAY['Geology Tools'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3037', ARRAY['Business Studies', 'Geography', 'Marine & Fisheries'], ARRAY['Fisheries Trade'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3030', ARRAY['Business Studies', 'Chemistry', 'Marine & Fisheries'], ARRAY['Marine Chem Biz'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3076', ARRAY['Core Mathematics', 'General Science', 'Media Technology'], ARRAY['Media Science'], 4.1, 'HIGH'),
((SELECT id FROM track), 'ST3077', ARRAY['Biology', 'Geography', 'Media Technology'], ARRAY['Nature Doc'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3036', ARRAY['Core Mathematics', 'Business Studies', 'Wood Work'], ARRAY['Construction Mgmt'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3039', ARRAY['Business Studies', 'Home Science', 'Marine & Fisheries'], ARRAY['Seafood Biz'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3119', ARRAY['Core Mathematics', 'General Science', 'Power Mechanics'], ARRAY['Mechanical Tech'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3111', ARRAY['Business Studies', 'Home Science', 'Power Mechanics'], ARRAY['Appliance Biz'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3069', ARRAY['Geography', 'Media Technology', 'Wood Work'], ARRAY['Set Systems'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'ST3116', ARRAY['Computer Studies', 'General Science', 'Power Mechanics'], ARRAY['Auto Systems'], 4.2, 'HIGH'),
((SELECT id FROM track), 'ST3012', ARRAY['Electricity', 'General Science', 'Media Technology'], ARRAY['AV Tech'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'ST3070', ARRAY['Business Studies', 'Home Science', 'Media Technology'], ARRAY['Home Ent'], 3.9, 'LOW'),
((SELECT id FROM track), 'ST3093', ARRAY['Computer Studies', 'General Science', 'Metal Work'], ARRAY['CNC Machining'], 4.3, 'HIGH'),
((SELECT id FROM track), 'ST3028', ARRAY['Biology', 'Business Studies', 'Marine & Fisheries'], ARRAY['Marine Bio Biz'], 4.2, 'MEDIUM'),
((SELECT id FROM track), 'ST3052', ARRAY['Biology', 'Geography', 'Marine & Fisheries'], ARRAY['Marine Ecology'], 4.2, 'MEDIUM')
ON CONFLICT (code) DO NOTHING;

-- 7. SOCIAL SCIENCES > HUMANITIES
WITH track AS (SELECT id FROM tracks WHERE code = 'HUM_BUS')
INSERT INTO subject_combinations (track_id, code, subjects, career_clusters, difficulty_rating, demand_level)
VALUES
((SELECT id FROM track), 'SS2033', ARRAY['Computer Studies', 'Geography', 'Islamic Religious Education'], ARRAY['GIS Islamic Studies'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2050', ARRAY['Christian Religious Education', 'Geography', 'Mandarine Chinese'], ARRAY['Intl Missions'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2019', ARRAY['Christian Religious Education', 'Geography', 'History & Citizenship'], ARRAY['Theology'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2112', ARRAY['Business Studies', 'Christian Religious Education', 'French'], ARRAY['Intl Commerce'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2055', ARRAY['Core Mathematics', 'Geography', 'Hindu Religious Education'], ARRAY['Demography'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'SS2099', ARRAY['Business Studies', 'German', 'History & Citizenship'], ARRAY['Economic History'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'SS2061', ARRAY['Business Studies', 'Geography', 'Literature in English'], ARRAY['Economic Geography'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2118', ARRAY['Business Studies', 'Geography', 'Kenya Sign Language'], ARRAY['Inclusive Biz'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2002', ARRAY['Business Studies', 'German', 'Hindu Religious Education'], ARRAY['Intl Trade'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2041', ARRAY['General Science', 'Geography', 'Hindu Religious Education'], ARRAY['Social Science'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2024', ARRAY['Computer Studies', 'Geography', 'History & Citizenship'], ARRAY['Digital Humanities'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS2092', ARRAY['Geography', 'History & Citizenship', 'Mandarine Chinese'], ARRAY['Diplomacy'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2057', ARRAY['Arabic', 'Christian Religious Education', 'History & Citizenship'], ARRAY['Religious Studies'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2004', ARRAY['Geography', 'History & Citizenship', 'Literature in English'], ARRAY['Liberal Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2065', ARRAY['Business Studies', 'Geography', 'Indigenous Language'], ARRAY['Local Development'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2056', ARRAY['Core Mathematics', 'Business Studies', 'Geography'], ARRAY['Economics'], 4.3, 'HIGH'),
((SELECT id FROM track), 'SS2003', ARRAY['Business Studies', 'German', 'Islamic Religious Education'], ARRAY['Intl Business'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2100', ARRAY['Business Studies', 'History & Citizenship', 'Literature in English'], ARRAY['Corporate Law'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS2091', ARRAY['Core Mathematics', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['History Analysis'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2042', ARRAY['General Science', 'Geography', 'Islamic Religious Education'], ARRAY['Social Science'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2110', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'Islamic Religious Education'], ARRAY['Business Admin'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2115', ARRAY['Business Studies', 'Christian Religious Education', 'General Science'], ARRAY['Ethical Business'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2101', ARRAY['Business Studies', 'History & Citizenship', 'Mandarine Chinese'], ARRAY['Intl Economics'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS2071', ARRAY['Fasihi ya Kiswahili', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['Cultural Studies'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS2013', ARRAY['General Science', 'Geography', 'History & Citizenship'], ARRAY['Social Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2044', ARRAY['Geography', 'German', 'Hindu Religious Education'], ARRAY['Intl Relations'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2039', ARRAY['French', 'Geography', 'Islamic Religious Education'], ARRAY['Diplomacy'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2069', ARRAY['Christian Religious Education', 'Fasihi ya Kiswahili', 'History & Citizenship'], ARRAY['Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS2064', ARRAY['Christian Religious Education', 'Computer Studies', 'History & Citizenship'], ARRAY['Digital Archives'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2086', ARRAY['Hindu Religious Education', 'History & Citizenship', 'Mandarine Chinese'], ARRAY['Asian Studies'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2018', ARRAY['Fasihi ya Kiswahili', 'Geography', 'History & Citizenship'], ARRAY['East African Studies'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2109', ARRAY['Business Studies', 'Christian Religious Education', 'Fasihi ya Kiswahili'], ARRAY['Business Admin'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2103', ARRAY['Arabic', 'Business Studies', 'Christian Religious Education'], ARRAY['Interfaith Biz'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2077', ARRAY['General Science', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Social Science'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2080', ARRAY['German', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Intl Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2035', ARRAY['Christian Religious Education', 'Fasihi ya Kiswahili', 'Geography'], ARRAY['Education'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS2094', ARRAY['Arabic', 'Business Studies', 'History & Citizenship'], ARRAY['Middle East Biz'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2026', ARRAY['Arabic', 'Geography', 'History & Citizenship'], ARRAY['Middle East Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2087', ARRAY['History & Citizenship', 'Islamic Religious Education', 'Mandarine Chinese'], ARRAY['Intl Relations'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2097', ARRAY['Business Studies', 'French', 'History & Citizenship'], ARRAY['Intl Trade'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS2027', ARRAY['Core Mathematics', 'Business Studies', 'Hindu Religious Education'], ARRAY['Finance'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS2083', ARRAY['History & Citizenship', 'Islamic Religious Education', 'Literature in English'], ARRAY['Liberal Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2116', ARRAY['Business Studies', 'General Science', 'Islamic Religious Education'], ARRAY['Business Admin'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2062', ARRAY['Computer Studies', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['Digital Humanities'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2005', ARRAY['Business Studies', 'Christian Religious Education', 'German'], ARRAY['Intl Commerce'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2012', ARRAY['Business Studies', 'Hindu Religious Education', 'Literature in English'], ARRAY['Intl Business'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2117', ARRAY['Business Studies', 'General Science', 'Hindu Religious Education'], ARRAY['Business Admin'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2052', ARRAY['Geography', 'Hindu Religious Education', 'Mandarine Chinese'], ARRAY['Asian Studies'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2098', ARRAY['Business Studies', 'General Science', 'History & Citizenship'], ARRAY['Economics'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2010', ARRAY['Geography', 'German', 'History & Citizenship'], ARRAY['European Studies'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2074', ARRAY['French', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Diplomacy'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2029', ARRAY['Arabic', 'Christian Religious Education', 'Geography'], ARRAY['Religious Studies'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2047', ARRAY['Christian Religious Education', 'Geography', 'Literature in English'], ARRAY['Education'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2025', ARRAY['Business Studies', 'Geography', 'History & Citizenship'], ARRAY['Humanities'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2105', ARRAY['Arabic', 'Business Studies', 'Hindu Religious Education'], ARRAY['Intl Trade'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2031', ARRAY['Arabic', 'Geography', 'Hindu Religious Education'], ARRAY['Cultural Geography'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2006', ARRAY['Business Studies', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['Economic History'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2017', ARRAY['Business Studies', 'Christian Religious Education', 'Mandarine Chinese'], ARRAY['Intl Business'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS2076', ARRAY['Christian Religious Education', 'General Science', 'History & Citizenship'], ARRAY['Social Science'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2085', ARRAY['Hindu Religious Education', 'History & Citizenship', 'Literature in English'], ARRAY['Liberal Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2070', ARRAY['Fasihi ya Kiswahili', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Cultural Studies'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2079', ARRAY['Christian Religious Education', 'German', 'History & Citizenship'], ARRAY['Euro History'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2032', ARRAY['Computer Studies', 'Geography', 'Hindu Religious Education'], ARRAY['Digital Humanities'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2089', ARRAY['Core Mathematics', 'Christian Religious Education', 'History & Citizenship'], ARRAY['Social Stats'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2063', ARRAY['Computer Studies', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Digital Humanities'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2093', ARRAY['Core Mathematics', 'Geography', 'History & Citizenship'], ARRAY['Geopolitics'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'SS2008', ARRAY['Business Studies', 'Christian Religious Education', 'History & Citizenship'], ARRAY['Business Ethics'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2038', ARRAY['French', 'Geography', 'Hindu Religious Education'], ARRAY['Cultural Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2009', ARRAY['Business Studies', 'Christian Religious Education', 'Literature in English'], ARRAY['Publishing'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2095', ARRAY['Business Studies', 'Computer Studies', 'History & Citizenship'], ARRAY['E-Commerce'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS2106', ARRAY['Business Studies', 'Christian Religious Education', 'Computer Studies'], ARRAY['Business Tech'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS2046', ARRAY['Christian Religious Education', 'Geography', 'German'], ARRAY['International Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2090', ARRAY['Core Mathematics', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Islamic Finance'], 4.1, 'MEDIUM'),
((SELECT id FROM track), 'SS2051', ARRAY['Geography', 'Islamic Religious Education', 'Mandarine Chinese'], ARRAY['Asian Studies'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2048', ARRAY['Geography', 'Islamic Religious Education', 'Literature in English'], ARRAY['Cultural Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2054', ARRAY['Core Mathematics', 'Geography', 'Islamic Religious Education'], ARRAY['Demography'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2034', ARRAY['Christian Religious Education', 'Computer Studies', 'Geography'], ARRAY['GIS'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2021', ARRAY['Core Mathematics', 'Business Studies', 'Christian Religious Education'], ARRAY['Accounting'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS2088', ARRAY['Christian Religious Education', 'History & Citizenship', 'Mandarine Chinese'], ARRAY['Intl Relations'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2023', ARRAY['Core Mathematics', 'Business Studies', 'Islamic Religious Education'], ARRAY['Islamic Banking'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS2108', ARRAY['Business Studies', 'Computer Studies', 'Hindu Religious Education'], ARRAY['Business Tech'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2058', ARRAY['Arabic', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Islamic History'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2049', ARRAY['Geography', 'Hindu Religious Education', 'Literature in English'], ARRAY['Cultural Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2082', ARRAY['Christian Religious Education', 'History & Citizenship', 'Literature in English'], ARRAY['Liberal Arts'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2113', ARRAY['Business Studies', 'French', 'Islamic Religious Education'], ARRAY['Intl Commerce'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2068', ARRAY['Business Studies', 'French', 'Geography'], ARRAY['Intl Logistics'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2081', ARRAY['German', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['History'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2059', ARRAY['Arabic', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['History'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2014', ARRAY['Business Studies', 'Hindu Religious Education', 'Mandarine Chinese'], ARRAY['Intl Business'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS2037', ARRAY['Fasihi ya Kiswahili', 'Geography', 'Hindu Religious Education'], ARRAY['Cultural Studies'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS2020', ARRAY['Geography', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['Asian History'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2104', ARRAY['Arabic', 'Business Studies', 'Islamic Religious Education'], ARRAY['Islamic Finance'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2030', ARRAY['Arabic', 'Geography', 'Islamic Religious Education'], ARRAY['Middle East Geo'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2066', ARRAY['Business Studies', 'Geography', 'German'], ARRAY['European Biz'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2015', ARRAY['Business Studies', 'Islamic Religious Education', 'Mandarine Chinese'], ARRAY['Intl Business'], 4.0, 'HIGH'),
((SELECT id FROM track), 'SS2084', ARRAY['Arabic', 'Business Studies', 'Geography'], ARRAY['Regional Trade'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2011', ARRAY['Business Studies', 'Islamic Religious Education', 'Literature in English'], ARRAY['Business Comms'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2022', ARRAY['Geography', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Islamic History'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2040', ARRAY['Christian Religious Education', 'French', 'Geography'], ARRAY['Dev Studies'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2067', ARRAY['Business Studies', 'General Science', 'Geography'], ARRAY['Economic Geo'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2016', ARRAY['French', 'Geography', 'History & Citizenship'], ARRAY['Euro Studies'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2111', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'Hindu Religious Education'], ARRAY['Business Admin'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2073', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'Geography'], ARRAY['Regional Biz'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2114', ARRAY['Business Studies', 'French', 'Hindu Religious Education'], ARRAY['Intl Commerce'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2102', ARRAY['Core Mathematics', 'Business Studies', 'History & Citizenship'], ARRAY['Economics'], 4.2, 'HIGH'),
((SELECT id FROM track), 'SS2078', ARRAY['General Science', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['Social Science'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2007', ARRAY['Business Studies', 'History & Citizenship', 'Islamic Religious Education'], ARRAY['Business History'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2107', ARRAY['Business Studies', 'Computer Studies', 'Islamic Religious Education'], ARRAY['Business Tech'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2043', ARRAY['Christian Religious Education', 'General Science', 'Geography'], ARRAY['Social Studies'], 3.7, 'LOW'),
((SELECT id FROM track), 'SS2096', ARRAY['Business Studies', 'Fasihi ya Kiswahili', 'History & Citizenship'], ARRAY['Public Admin'], 3.8, 'LOW'),
((SELECT id FROM track), 'SS2053', ARRAY['Core Mathematics', 'Christian Religious Education', 'Geography'], ARRAY['Demography'], 4.0, 'MEDIUM'),
((SELECT id FROM track), 'SS2060', ARRAY['Business Studies', 'Geography', 'Mandarine Chinese'], ARRAY['Intl Logistics'], 4.1, 'HIGH'),
((SELECT id FROM track), 'SS2001', ARRAY['Business Studies', 'Christian Religious Education', 'Geography'], ARRAY['Dev Economics'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2045', ARRAY['Geography', 'German', 'Islamic Religious Education'], ARRAY['Intl Studies'], 3.9, 'LOW'),
((SELECT id FROM track), 'SS2072', ARRAY['French', 'Hindu Religious Education', 'History & Citizenship'], ARRAY['Diplomacy'], 3.9, 'MEDIUM'),
((SELECT id FROM track), 'SS2036', ARRAY['Fasihi ya Kiswahili', 'Geography', 'Islamic Religious Education'], ARRAY['Cultural Studies'], 3.6, 'LOW'),
((SELECT id FROM track), 'SS2075', ARRAY['Christian Religious Education', 'French', 'History & Citizenship'], ARRAY['Diplomacy'], 3.8, 'LOW')
ON CONFLICT (code) DO NOTHING;
